-- SQL Assignment 1

-- 1. New Customers Acquired in June 2023
SELECT 
    per.PARTY_ID,
    per.FIRST_NAME,
    per.LAST_NAME,
    cm.INFO_STRING AS EMAIL,
    tn.CONTACT_NUMBER AS PHONE,
    per.CREATED_DATE AS ENTRY_DATE
FROM PERSON per
INNER JOIN PARTY_ROLE pr ON per.PARTY_ID = pr.PARTY_ID
LEFT JOIN (
    PARTY_CONTACT_MECH pcm_email 
    INNER JOIN CONTACT_MECH cm 
        ON pcm_email.CONTACT_MECH_ID = cm.CONTACT_MECH_ID 
        AND cm.CONTACT_MECH_TYPE_ID = 'EMAIL_ADDRESS'
) ON per.PARTY_ID = pcm_email.PARTY_ID
LEFT JOIN (
    PARTY_CONTACT_MECH pcm_phone 
    INNER JOIN TELECOM_NUMBER tn 
        ON pcm_phone.CONTACT_MECH_ID = tn.CONTACT_MECH_ID
) ON per.PARTY_ID = pcm_phone.PARTY_ID
WHERE 
    pr.ROLE_TYPE_ID = 'CUSTOMER' 
    AND per.CREATED_DATE >= '2023-06-01' 
    AND per.CREATED_DATE < '2023-07-01';

-- 2. List All Active Physical Products
SELECT DISTINCT
    p.PRODUCT_ID, 
    p.PRODUCT_TYPE_ID, 
    p.INTERNAL_NAME
FROM PRODUCT p
INNER JOIN PRODUCT_TYPE pt ON p.PRODUCT_TYPE_ID = pt.PRODUCT_TYPE_ID
INNER JOIN PRODUCT_CATEGORY_MEMBER pcm ON p.PRODUCT_ID = pcm.PRODUCT_ID 
WHERE 
    pt.IS_PHYSICAL = 'Y' 
    AND pcm.FROM_DATE <= CURRENT_TIMESTAMP
    AND (pcm.THRU_DATE IS NULL OR pcm.THRU_DATE > CURRENT_TIMESTAMP);

-- 3. Products Missing NetSuite ID
SELECT 
    p.PRODUCT_ID, 
    p.INTERNAL_NAME,
    p.PRODUCT_TYPE_ID,
    gi.GOOD_IDENTIFICATION_TYPE_ID AS NETSUITE_ID
FROM PRODUCT p
LEFT JOIN GOOD_IDENTIFICATION gi 
    ON p.PRODUCT_ID = gi.PRODUCT_ID 
    AND gi.GOOD_IDENTIFICATION_TYPE_ID = 'NETSUITE_ID'
WHERE 
    gi.ID_VALUE IS NULL 
    OR gi.ID_VALUE = '';

-- 4. Product IDs Across Systems
SELECT 
    p.PRODUCT_ID AS PRODUCT_ID,
    gi_shopify.ID_VALUE AS SHOPIFY_ID,
    p.PRODUCT_ID AS HOTWAX_ID,
    gi_erp.ID_VALUE AS ERP_ID
FROM PRODUCT p
LEFT JOIN GOOD_IDENTIFICATION gi_shopify 
    ON p.PRODUCT_ID = gi_shopify.PRODUCT_ID 
    AND gi_shopify.GOOD_IDENTIFICATION_TYPE_ID = 'SHOPIFY_ID'
LEFT JOIN GOOD_IDENTIFICATION gi_erp 
    ON p.PRODUCT_ID = gi_erp.PRODUCT_ID 
    AND gi_erp.GOOD_IDENTIFICATION_TYPE_ID = 'NETSUITE_ID';

-- 5. Completed Orders in August 2023
SELECT 
    oi.PRODUCT_ID,
    p.PRODUCT_TYPE_ID,
    oh.PRODUCT_STORE_ID,
    oi.QUANTITY AS TOTAL_QUANTITY,
    p.INTERNAL_NAME,
    oisg.FACILITY_ID,
    oh.EXTERNAL_ID,
    f.FACILITY_TYPE_ID,
    oh.ORDER_ID,
    oi.ORDER_ITEM_SEQ_ID,
    oisg.SHIP_GROUP_SEQ_ID
FROM ORDER_HEADER oh
INNER JOIN ORDER_ITEM oi ON oh.ORDER_ID = oi.ORDER_ID
INNER JOIN PRODUCT p ON oi.PRODUCT_ID = p.PRODUCT_ID
INNER JOIN ORDER_ITEM_SHIP_GROUP oisg ON oh.ORDER_ID = oisg.ORDER_ID
LEFT JOIN FACILITY f ON oisg.FACILITY_ID = f.FACILITY_ID
WHERE 
    oh.STATUS_ID = 'ORDER_COMPLETED'
    AND oh.ORDER_DATE >= '2023-08-01' 
    AND oh.ORDER_DATE < '2023-09-01';

-- 7. Newly Created Sales Orders and Payment Methods
SELECT 
    oh.ORDER_ID,
    oh.GRAND_TOTAL AS TOTAL_AMOUNT,
    opp.PAYMENT_METHOD_TYPE_ID AS PAYMENT_METHOD,
    oh.EXTERNAL_ID AS "Shopify Order ID"
FROM ORDER_HEADER oh
INNER JOIN ORDER_PAYMENT_PREFERENCE opp ON oh.ORDER_ID = opp.ORDER_ID
WHERE 
    oh.ORDER_TYPE_ID = 'SALES_ORDER'
    AND oh.STATUS_ID = 'ORDER_CREATED';

-- 8. Payment Captured but Not Shipped
SELECT 
    oh.ORDER_ID,
    oh.STATUS_ID AS ORDER_STATUS,
    opp.STATUS_ID AS PAYMENT_STATUS,
    oisg.STATUS_ID AS SHIPMENT_STATUS
FROM ORDER_HEADER oh
INNER JOIN ORDER_PAYMENT_PREFERENCE opp ON oh.ORDER_ID = opp.ORDER_ID
INNER JOIN ORDER_ITEM_SHIP_GROUP oisg ON oh.ORDER_ID = oisg.ORDER_ID
WHERE 
    opp.STATUS_ID = 'PAYMENT_RECEIVED'
    AND oisg.STATUS_ID NOT IN ('SHIP_GROUP_SHIPPED', 'SHIP_GROUP_DELIVERED');

-- 9. Orders Completed Hourly
SELECT 
    EXTRACT(HOUR FROM ORDER_DATE) AS HOUR,
    COUNT(ORDER_ID) AS "TOTAL ORDERS"
FROM ORDER_HEADER
WHERE 
    STATUS_ID = 'ORDER_COMPLETED'
GROUP BY 
    EXTRACT(HOUR FROM ORDER_DATE)
ORDER BY 
    HOUR;

-- 10. BOPIS Orders Revenue (Last Year)
SELECT 
    COUNT(DISTINCT oh.ORDER_ID) AS "TOTAL ORDERS",
    SUM(oh.GRAND_TOTAL) AS "TOTAL REVENUE"
FROM ORDER_HEADER oh
INNER JOIN ORDER_ITEM_SHIP_GROUP oisg ON oh.ORDER_ID = oisg.ORDER_ID
WHERE 
    oisg.SHIPMENT_METHOD_TYPE_ID = 'STORE_PICKUP'
    AND oh.ORDER_DATE >= DATE_SUB(CURRENT_DATE, INTERVAL 1 YEAR)
    AND oh.ORDER_DATE < CURRENT_DATE;

-- 11. Canceled Orders (Last Month)
SELECT 
    COUNT(DISTINCT oh.ORDER_ID) AS "TOTAL ORDERS",
    os.CHANGE_REASON AS "CANCELATION REASON"
FROM ORDER_HEADER oh
INNER JOIN ORDER_STATUS os ON oh.ORDER_ID = os.ORDER_ID
WHERE 
    oh.STATUS_ID = 'ORDER_CANCELLED'
    AND os.STATUS_ID = 'ORDER_CANCELLED'
    AND MONTH(oh.ORDER_DATE) = MONTH(CURRENT_DATE - INTERVAL 1 MONTH)
    AND YEAR(oh.ORDER_DATE) = YEAR(CURRENT_DATE - INTERVAL 1 MONTH)
GROUP BY 
    os.CHANGE_REASON;

-- 12. Product Threshold Value
SELECT 
    PRODUCT_ID,
    MINIMUM_STOCK AS THRESHOLD
FROM PRODUCT_FACILITY
WHERE 
    MINIMUM_STOCK IS NOT NULL;