-- SQL Assignment 2

-- 5.1 Shipping Addresses for October 2023 Orders
SELECT 
    oh.ORDER_ID,
    oc.PARTY_ID,
    CONCAT(per.FIRST_NAME, ' ', per.LAST_NAME) AS CUSTOMER_NAME,
    pa.ADDRESS1 AS STREET_ADDRESS,
    pa.CITY,
    pa.STATE_PROVINCE_GEO_ID AS STATE_PROVINCE,
    pa.POSTAL_CODE,
    pa.COUNTRY_GEO_ID AS COUNTRY_CODE,
    oh.STATUS_ID AS ORDER_STATUS,
    oh.ORDER_DATE
FROM ORDER_HEADER oh
INNER JOIN ORDER_CONTACT_MECH ocm ON oh.ORDER_ID = ocm.ORDER_ID 
    AND ocm.CONTACT_MECH_PURPOSE_TYPE_ID = 'SHIPPING_LOCATION'
INNER JOIN POSTAL_ADDRESS pa ON ocm.CONTACT_MECH_ID = pa.CONTACT_MECH_ID
INNER JOIN ORDER_ROLE oc ON oh.ORDER_ID = oc.ORDER_ID AND oc.ROLE_TYPE_ID = 'PLACING_CUSTOMER'
INNER JOIN PERSON per ON oc.PARTY_ID = per.PARTY_ID
WHERE 
    oh.ORDER_DATE >= '2023-10-01' 
    AND oh.ORDER_DATE < '2023-11-01';

-- 5.2 Orders from New York
SELECT 
    oh.ORDER_ID,
    CONCAT(per.FIRST_NAME, ' ', per.LAST_NAME) AS CUSTOMER_NAME,
    pa.ADDRESS1 AS STREET_ADDRESS,
    pa.CITY,
    pa.STATE_PROVINCE_GEO_ID AS STATE_PROVINCE,
    pa.POSTAL_CODE,
    oh.GRAND_TOTAL AS TOTAL_AMOUNT,
    oh.ORDER_DATE,
    oh.STATUS_ID AS ORDER_STATUS
FROM ORDER_HEADER oh
INNER JOIN ORDER_CONTACT_MECH ocm ON oh.ORDER_ID = ocm.ORDER_ID 
    AND ocm.CONTACT_MECH_PURPOSE_TYPE_ID = 'SHIPPING_LOCATION'
INNER JOIN POSTAL_ADDRESS pa ON ocm.CONTACT_MECH_ID = pa.CONTACT_MECH_ID
INNER JOIN ORDER_ROLE oc ON oh.ORDER_ID = oc.ORDER_ID AND oc.ROLE_TYPE_ID = 'PLACING_CUSTOMER'
INNER JOIN PERSON per ON oc.PARTY_ID = per.PARTY_ID
WHERE 
    pa.STATE_PROVINCE_GEO_ID = 'NY';

-- 5.3 Top-Selling Product in New York
SELECT 
    oi.PRODUCT_ID,
    p.INTERNAL_NAME,
    SUM(oi.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    pa.STATE_PROVINCE_GEO_ID AS STATE,
    SUM(oi.QUANTITY * oi.UNIT_PRICE) AS REVENUE
FROM ORDER_HEADER oh
INNER JOIN ORDER_ITEM oi ON oh.ORDER_ID = oi.ORDER_ID
INNER JOIN PRODUCT p ON oi.PRODUCT_ID = p.PRODUCT_ID
INNER JOIN ORDER_CONTACT_MECH ocm ON oh.ORDER_ID = ocm.ORDER_ID 
    AND ocm.CONTACT_MECH_PURPOSE_TYPE_ID = 'SHIPPING_LOCATION'
INNER JOIN POSTAL_ADDRESS pa ON ocm.CONTACT_MECH_ID = pa.CONTACT_MECH_ID
WHERE 
    pa.STATE_PROVINCE_GEO_ID = 'NY'
    AND oh.STATUS_ID = 'ORDER_COMPLETED'
GROUP BY 
    oi.PRODUCT_ID,
    p.INTERNAL_NAME,
    pa.STATE_PROVINCE_GEO_ID
ORDER BY 
    TOTAL_QUANTITY_SOLD DESC
LIMIT 1;

-- 7.3 Store-Specific (Facility-Wise) Revenue
SELECT 
    f.FACILITY_ID,
    f.FACILITY_NAME,
    COUNT(DISTINCT oh.ORDER_ID) AS TOTAL_ORDERS,
    SUM(oh.GRAND_TOTAL) AS TOTAL_REVENUE
FROM ORDER_HEADER oh
INNER JOIN ORDER_ITEM_SHIP_GROUP oisg ON oh.ORDER_ID = oisg.ORDER_ID
INNER JOIN FACILITY f ON oisg.FACILITY_ID = f.FACILITY_ID
WHERE 
    oh.STATUS_ID = 'ORDER_COMPLETED'
GROUP BY 
    f.FACILITY_ID,
    f.FACILITY_NAME;

-- 8.1 Lost and Damaged Inventory
SELECT 
    iid.INVENTORY_ITEM_ID,
    ii.PRODUCT_ID,
    ii.FACILITY_ID,
    iid.QUANTITY_ON_HAND_DIFF AS QUANTITY_LOST_OR_DAMAGED,
    iid.VARIANCE_REASON_ID AS REASON_CODE,
    iid.EFFECTIVE_DATE AS TRANSACTION_DATE
FROM INVENTORY_ITEM_DETAIL iid
INNER JOIN INVENTORY_ITEM ii ON iid.INVENTORY_ITEM_ID = ii.INVENTORY_ITEM_ID
WHERE 
    iid.VARIANCE_REASON_ID IN ('VAR_LOST', 'VAR_DAMAGED');

-- 8.2 Low Stock or Out of Stock Items Report
SELECT 
    ii.PRODUCT_ID,
    p.INTERNAL_NAME AS PRODUCT_NAME,
    ii.FACILITY_ID,
    SUM(ii.QUANTITY_ON_HAND_TOTAL) AS QOH,
    SUM(ii.AVAILABLE_TO_PROMISE_TOTAL) AS ATP,
    pf.MINIMUM_STOCK AS REORDER_THRESHOLD,
    CURRENT_DATE AS DATE_CHECKED
FROM INVENTORY_ITEM ii
INNER JOIN PRODUCT p ON ii.PRODUCT_ID = p.PRODUCT_ID
INNER JOIN PRODUCT_FACILITY pf ON ii.PRODUCT_ID = pf.PRODUCT_ID AND ii.FACILITY_ID = pf.FACILITY_ID
GROUP BY 
    ii.PRODUCT_ID,
    p.INTERNAL_NAME,
    ii.FACILITY_ID,
    pf.MINIMUM_STOCK
HAVING 
    SUM(ii.AVAILABLE_TO_PROMISE_TOTAL) <= pf.MINIMUM_STOCK 
    OR SUM(ii.AVAILABLE_TO_PROMISE_TOTAL) <= 0;

-- 8.3 Retrieve the Current Facility (Physical or Virtual) of Open Orders
SELECT 
    oh.ORDER_ID,
    oh.STATUS_ID AS ORDER_STATUS,
    f.FACILITY_ID,
    f.FACILITY_NAME,
    f.FACILITY_TYPE_ID
FROM ORDER_HEADER oh
INNER JOIN ORDER_ITEM_SHIP_GROUP oisg ON oh.ORDER_ID = oisg.ORDER_ID
LEFT JOIN FACILITY f ON oisg.FACILITY_ID = f.FACILITY_ID
WHERE 
    oh.STATUS_ID = 'ORDER_APPROVED';

-- 8.4 Items Where QOH and ATP Differ
SELECT 
    PRODUCT_ID,
    FACILITY_ID,
    SUM(QUANTITY_ON_HAND_TOTAL) AS QOH,
    SUM(AVAILABLE_TO_PROMISE_TOTAL) AS ATP,
    (SUM(QUANTITY_ON_HAND_TOTAL) - SUM(AVAILABLE_TO_PROMISE_TOTAL)) AS DIFFERENCE
FROM INVENTORY_ITEM
GROUP BY 
    PRODUCT_ID,
    FACILITY_ID
HAVING 
    SUM(QUANTITY_ON_HAND_TOTAL) != SUM(AVAILABLE_TO_PROMISE_TOTAL);

-- 8.5 Order Item Current Status Changed Date-Time
SELECT 
    oi.ORDER_ID,
    oi.ORDER_ITEM_SEQ_ID,
    oi.STATUS_ID AS CURRENT_STATUS_ID,
    ois.STATUS_DATETIME AS STATUS_CHANGE_DATETIME,
    ois.STATUS_USER_LOGIN AS CHANGED_BY
FROM ORDER_ITEM oi
INNER JOIN ORDER_ITEM_STATUS ois ON oi.ORDER_ID = ois.ORDER_ID 
    AND oi.ORDER_ITEM_SEQ_ID = ois.ORDER_ITEM_SEQ_ID
    AND oi.STATUS_ID = ois.STATUS_ID;

-- 8.6 Total Orders by Sales Channel
SELECT 
    oh.SALES_CHANNEL_ENUM_ID AS SALES_CHANNEL,
    COUNT(DISTINCT oh.ORDER_ID) AS TOTAL_ORDERS,
    SUM(oh.GRAND_TOTAL) AS TOTAL_REVENUE
FROM ORDER_HEADER oh
GROUP BY 
    oh.SALES_CHANNEL_ENUM_ID;