-- SQL Assignment 3

-- 1. Completed Sales Orders (Physical Items)
SELECT 
    oh.ORDER_ID,
    oi.ORDER_ITEM_SEQ_ID,
    oi.PRODUCT_ID,
    pt.PRODUCT_TYPE_ID,
    oh.SALES_CHANNEL_ENUM_ID,
    oh.ORDER_DATE,
    oh.ENTRY_DATE,
    oh.STATUS_ID,
    os.STATUS_DATETIME,
    oh.ORDER_TYPE_ID,
    oh.PRODUCT_STORE_ID
FROM ORDER_HEADER oh
INNER JOIN ORDER_ITEM oi ON oh.ORDER_ID = oi.ORDER_ID
INNER JOIN PRODUCT p ON oi.PRODUCT_ID = p.PRODUCT_ID
INNER JOIN PRODUCT_TYPE pt ON p.PRODUCT_TYPE_ID = pt.PRODUCT_TYPE_ID
INNER JOIN ORDER_STATUS os ON oh.ORDER_ID = os.ORDER_ID AND oh.STATUS_ID = os.STATUS_ID
WHERE 
    oh.ORDER_TYPE_ID = 'SALES_ORDER'
    AND oh.STATUS_ID = 'ORDER_COMPLETED'
    AND pt.IS_PHYSICAL = 'Y';

-- 2. Completed Return Items
SELECT 
    rh.RETURN_ID,
    ri.ORDER_ID,
    rh.PRODUCT_STORE_ID,
    rs.STATUS_DATETIME,
    oh.ORDER_NAME,
    rh.FROM_PARTY_ID,
    rh.RETURN_DATE,
    rh.ENTRY_DATE,
    rh.RETURN_CHANNEL_ENUM_ID
FROM RETURN_HEADER rh
INNER JOIN RETURN_ITEM ri ON rh.RETURN_ID = ri.RETURN_ID
LEFT JOIN ORDER_HEADER oh ON ri.ORDER_ID = oh.ORDER_ID
INNER JOIN RETURN_STATUS rs ON rh.RETURN_ID = rs.RETURN_ID AND rh.STATUS_ID = rs.STATUS_ID
WHERE 
    rh.STATUS_ID = 'RETURN_COMPLETED';

-- 3. Single-Return Orders (Last Month)
SELECT 
    per.PARTY_ID,
    per.FIRST_NAME
FROM RETURN_HEADER rh
INNER JOIN RETURN_ITEM ri ON rh.RETURN_ID = ri.RETURN_ID
INNER JOIN PERSON per ON rh.FROM_PARTY_ID = per.PARTY_ID
WHERE 
    MONTH(rh.RETURN_DATE) = MONTH(CURRENT_DATE - INTERVAL 1 MONTH)
    AND YEAR(rh.RETURN_DATE) = YEAR(CURRENT_DATE - INTERVAL 1 MONTH)
GROUP BY 
    ri.ORDER_ID, per.PARTY_ID, per.FIRST_NAME
HAVING 
    COUNT(DISTINCT rh.RETURN_ID) = 1;

-- 4. Returns and Appeasements
SELECT 
    COUNT(DISTINCT CASE WHEN ra.RETURN_ADJUSTMENT_TYPE_ID NOT IN ('APPEASEMENT') THEN rh.RETURN_ID END) AS "TOTAL RETURNS",
    SUM(CASE WHEN ra.RETURN_ADJUSTMENT_TYPE_ID NOT IN ('APPEASEMENT') THEN ra.AMOUNT ELSE 0 END) AS "RETURN $ TOTAL",
    COUNT(DISTINCT CASE WHEN ra.RETURN_ADJUSTMENT_TYPE_ID = 'APPEASEMENT' THEN rh.RETURN_ID END) AS "TOTAL APPEASEMENTS",
    SUM(CASE WHEN ra.RETURN_ADJUSTMENT_TYPE_ID = 'APPEASEMENT' THEN ra.AMOUNT ELSE 0 END) AS "APPEASEMENTS $ TOTAL"
FROM RETURN_HEADER rh
LEFT JOIN RETURN_ADJUSTMENT ra ON rh.RETURN_ID = ra.RETURN_ID;

-- 5. Detailed Return Information
SELECT 
    rh.RETURN_ID,
    rh.ENTRY_DATE,
    ra.RETURN_ADJUSTMENT_TYPE_ID,
    ra.AMOUNT,
    ra.COMMENTS,
    ri.ORDER_ID,
    oh.ORDER_DATE,
    rh.RETURN_DATE,
    rh.PRODUCT_STORE_ID
FROM RETURN_HEADER rh
INNER JOIN RETURN_ITEM ri ON rh.RETURN_ID = ri.RETURN_ID
LEFT JOIN RETURN_ADJUSTMENT ra ON rh.RETURN_ID = ra.RETURN_ID AND ri.RETURN_ITEM_SEQ_ID = ra.RETURN_ITEM_SEQ_ID
LEFT JOIN ORDER_HEADER oh ON ri.ORDER_ID = oh.ORDER_ID;

-- 6. Orders with Multiple Returns
SELECT 
    ri.ORDER_ID,
    rh.RETURN_ID,
    rh.RETURN_DATE,
    ri.RETURN_REASON_ID AS RETURN_REASON,
    ri.RETURN_QUANTITY
FROM RETURN_HEADER rh
INNER JOIN RETURN_ITEM ri ON rh.RETURN_ID = ri.RETURN_ID
WHERE 
    ri.ORDER_ID IN (
        SELECT ORDER_ID 
        FROM RETURN_ITEM 
        GROUP BY ORDER_ID 
        HAVING COUNT(DISTINCT RETURN_ID) > 1
    );

-- 7. Store with Most One-Day Shipped Orders (Last Month)
SELECT 
    f.FACILITY_ID,
    f.FACILITY_NAME,
    COUNT(DISTINCT oh.ORDER_ID) AS TOTAL_ONE_DAY_SHIP_ORDERS,
    DATE_FORMAT(CURRENT_DATE - INTERVAL 1 MONTH, '%Y-%m') AS REPORTING_PERIOD
FROM ORDER_HEADER oh
INNER JOIN ORDER_ITEM_SHIP_GROUP oisg ON oh.ORDER_ID = oisg.ORDER_ID
INNER JOIN FACILITY f ON oisg.FACILITY_ID = f.FACILITY_ID
WHERE 
    oisg.SHIPMENT_METHOD_TYPE_ID = 'NEXT_DAY'
    AND MONTH(oh.ORDER_DATE) = MONTH(CURRENT_DATE - INTERVAL 1 MONTH)
    AND YEAR(oh.ORDER_DATE) = YEAR(CURRENT_DATE - INTERVAL 1 MONTH)
GROUP BY 
    f.FACILITY_ID,
    f.FACILITY_NAME
ORDER BY 
    TOTAL_ONE_DAY_SHIP_ORDERS DESC
LIMIT 1;

-- 8. List of Warehouse Pickers
SELECT 
    per.PARTY_ID,
    CONCAT(per.FIRST_NAME, ' ', per.LAST_NAME) AS NAME,
    fr.ROLE_TYPE_ID,
    fr.FACILITY_ID,
    p.STATUS_ID AS STATUS
FROM FACILITY_ROLE fr
INNER JOIN PERSON per ON fr.PARTY_ID = per.PARTY_ID
INNER JOIN PARTY p ON per.PARTY_ID = p.PARTY_ID
WHERE 
    fr.ROLE_TYPE_ID = 'WAREHOUSE_PICKER';

-- 9. Total Facilities That Sell the Product
SELECT 
    pf.PRODUCT_ID,
    p.INTERNAL_NAME AS PRODUCT_NAME,
    COUNT(DISTINCT pf.FACILITY_ID) AS FACILITY_COUNT
FROM PRODUCT_FACILITY pf
INNER JOIN PRODUCT p ON pf.PRODUCT_ID = p.PRODUCT_ID
GROUP BY 
    pf.PRODUCT_ID,
    p.INTERNAL_NAME;

-- 10. Total Items in Various Virtual Facilities
SELECT 
    ii.PRODUCT_ID,
    f.FACILITY_ID,
    f.FACILITY_TYPE_ID,
    SUM(ii.QUANTITY_ON_HAND_TOTAL) AS QOH,
    SUM(ii.AVAILABLE_TO_PROMISE_TOTAL) AS ATP
FROM INVENTORY_ITEM ii
INNER JOIN FACILITY f ON ii.FACILITY_ID = f.FACILITY_ID
WHERE 
    f.FACILITY_TYPE_ID != 'VIRTUAL_FACILITY'
GROUP BY 
    ii.PRODUCT_ID,
    f.FACILITY_ID,
    f.FACILITY_TYPE_ID;

-- 11. Transfer Orders Without Inventory Reservation
SELECT 
    oh.ORDER_ID AS TRANSFER_ORDER_ID,
    oisg.FACILITY_ID AS FROM_FACILITY_ID, 
    oh.ORIGIN_FACILITY_ID AS TO_FACILITY_ID,
    oi.PRODUCT_ID,
    oi.QUANTITY AS REQUESTED_QUANTITY,
    COALESCE(SUM(oir.QUANTITY), 0) AS RESERVED_QUANTITY,
    oh.ORDER_DATE AS TRANSFER_DATE,
    oh.STATUS_ID AS STATUS
FROM ORDER_HEADER oh
INNER JOIN ORDER_ITEM oi ON oh.ORDER_ID = oi.ORDER_ID
LEFT JOIN ORDER_ITEM_SHIP_GROUP oisg ON oh.ORDER_ID = oisg.ORDER_ID
LEFT JOIN ORDER_ITEM_SHIP_GRP_INV_RES oir ON oi.ORDER_ID = oir.ORDER_ID AND oi.ORDER_ITEM_SEQ_ID = oir.ORDER_ITEM_SEQ_ID
WHERE 
    oh.ORDER_TYPE_ID = 'TRANSFER_ORDER'
GROUP BY 
    oh.ORDER_ID, oisg.FACILITY_ID, oh.ORIGIN_FACILITY_ID, oi.PRODUCT_ID, oi.QUANTITY, oh.ORDER_DATE, oh.STATUS_ID
HAVING 
    COALESCE(SUM(oir.QUANTITY), 0) = 0;

-- 12. Orders Without Picklist
SELECT 
    oh.ORDER_ID,
    oh.ORDER_DATE,
    oh.STATUS_ID AS ORDER_STATUS,
    oisg.FACILITY_ID,
    DATEDIFF(CURRENT_DATE, oh.ORDER_DATE) AS DURATION
FROM ORDER_HEADER oh
INNER JOIN ORDER_ITEM_SHIP_GROUP oisg ON oh.ORDER_ID = oisg.ORDER_ID
LEFT JOIN PICKLIST_BIN pb ON oh.ORDER_ID = pb.PRIMARY_ORDER_ID
WHERE 
    oh.STATUS_ID = 'ORDER_APPROVED'
    AND pb.PICKLIST_ID IS NULL;